version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - odoo-network

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-network
#    command: [ "odoo", "-d", "odoo", "-i", "base", "--stop-after-init" ] #first time run this with docker-compose up --build ...... docker-compose down
    command: ["--", "-i", "base"] #next time run this with docker-compose up --build ...... docker-compose down
#    command: ["odoo", "-d", "odoo", "-u", "custom_modules", "--without-demo=all"]

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoo-network: