services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - odoo-network

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-network
    command: [ "odoo", "-d", "odoo", "--without-demo=all" ]
  # run this separately if odoo server shows error:
  #    docker-compose run --rm odoo odoo -d odoo -i base --stop-after-init --without-demo=all

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=2GB
    ports:
      - "9090:9090"
    networks:
      - odoo-network
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - odoo-network
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - odoo-network
    ports:
      - "9100:9100"
    restart: unless-stopped

  app:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      #      - /run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped
    networks:
      - odoo-network

volumes:
  odoo-db-data:
  odoo-web-data:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  portainer-data:
    driver: local

networks:
  odoo-network: